### ISSUE TITLE
need ClientData.....(Full maps)

### ISSUE THREAD

**Issue by Arshiya051** [The-Legion-Preservation-Project/LegionCore-7.3.5#112]
hello I need complete data(maps). Of course, I was able to extract it myself, but because my game is build 25937, it cannot be extracted completely. and gives many errors. If you have the complete data(maps), please share. thank you
Or give a link to download the game with build 26972 so that I can download the full game and extract the maps from it.

**Comment by Etoyspeh** [comment]
@Arshiya051 hello
I can share my link to the maps I use, they were made from pure 7.3.5 26972 - https://mega.nz/file/TYklQA5b#8q6G180IoZXqmx2qcT_ETJ90HDH9Gja7FmLPrQ5Bc-U.
Unfortunately wowdl no longer works, you could download the client there.
It remains only to look for you yourself.

**Comment by d3athbl0w** [comment]
![image](https://github.com/user-attachments/assets/4270ab17-32d2-4c74-b278-be569512a71e)
Same errors

**Comment by Arshiya051** [comment]
> @Arshiya051 hello I can share my link to the maps I use, they were made from pure 7.3.5 26972 - https://mega.nz/file/TYklQA5b#8q6G180IoZXqmx2qcT_ETJ90HDH9Gja7FmLPrQ5Bc-U. Unfortunately wowdl no longer works, you could download the client there. It remains only to look for you yourself.

not Good....
I searched and found and downloaded this data. https://mega.nz/file/OIsBkYSY#zcbbwcV4uwl1xKC7k4Qs7gNEBpYyS7kofEqOiwk5KtY
 This is the best data.
But it still gives an error and even after creating an account, it does not enter the game and the server crashes.

**Comment by Arshiya051** [comment]
> ![image](https://private-user-images.githubusercontent.com/14060040/382208658-4270ab17-32d2-4c74-b278-be569512a71e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDUzNjgsIm5iZiI6MTczMDQ0NTA2OCwicGF0aCI6Ii8xNDA2MDA0MC8zODIyMDg2NTgtNDI3MGFiMTctMzJkMi00Yzc0LWIyNzgtYmU1Njk1MTJhNzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA3MTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMGVjM2YzMzAwOGUwNjI2MDAyZTNhMTA5NmI3ZTEzOGE2MDFiZjcxNmQ0YmE1MWVkYjA5ZDUwMzdhODA1NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qGL0PK9qW-KqwyZCa43KmFXNEqQNIJ3BbFgKWBSuONg) Same errors

Were you able to enter the game?
Even though there are these errors, the server still fails and is ready to enter...
But after entering the username and password, the server crashes and does not log in.

**Comment by Etoyspeh** [comment]
> > @Arshiya051 hello I can share my link to the maps I use, they were made from pure 7.3.5 26972 - https://mega.nz/file/TYklQA5b#8q6G180IoZXqmx2qcT_ETJ90HDH9Gja7FmLPrQ5Bc-U. Unfortunately wowdl no longer works, you could download the client there. It remains only to look for you yourself.
> 
> @Etoyspeh not Good.... I searched and found and downloaded this data. https://mega.nz/file/OIsBkYSY#zcbbwcV4uwl1xKC7k4Qs7gNEBpYyS7kofEqOiwk5KtY This is the best data. But it still gives an error and even after creating an account, it does not enter the game and the server crashes.

What's the password for the archive?
I want to try these maps

**Comment by jasongdove** [comment]
> ![image](https://private-user-images.githubusercontent.com/14060040/382208658-4270ab17-32d2-4c74-b278-be569512a71e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NTgxMjQsIm5iZiI6MTczMDU1NzgyNCwicGF0aCI6Ii8xNDA2MDA0MC8zODIyMDg2NTgtNDI3MGFiMTctMzJkMi00Yzc0LWIyNzgtYmU1Njk1MTJhNzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE0MzAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmOGFlMTIzZjE3YjA5ODFhMjQ5M2NkMGZhNDEwNmEzODNjZjc5NDlmMjA0ZWEyNzQ3ZDc5NDMyOTAxOGVjZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CLdQog33eAmmNKibSW3iJEdpBwTEiT6pGiqVdd7hC7w) Same errors

This is probably not really an error and is related to transports. The best data for this core is data using this core's tools.

**Comment by Arshiya051** [comment]
> > > @Arshiya051 hello I can share my link to the maps I use, they were made from pure 7.3.5 26972 - https://mega.nz/file/TYklQA5b#8q6G180IoZXqmx2qcT_ETJ90HDH9Gja7FmLPrQ5Bc-U. Unfortunately wowdl no longer works, you could download the client there. It remains only to look for you yourself.
> > 
> > 
> > @Etoyspeh not Good.... I searched and found and downloaded this data. https://mega.nz/file/OIsBkYSY#zcbbwcV4uwl1xKC7k4Qs7gNEBpYyS7kofEqOiwk5KtY This is the best data. But it still gives an error and even after creating an account, it does not enter the game and the server crashes.
> 
> What's the password for the archive? I want to try these maps

Emucoach

**Comment by jasongdove** [comment]
Emucoach data is used by old version of this core. The only data that should be used now is data that is extracted using the core's current tools. If you have a client to play with, you have a client that you can extract data from.
