### ISSUE TITLE
Warlock/Pet: pets no longer use their abilities.

### ISSUE THREAD

**Issue by 3nei** [The-Legion-Preservation-Project/LegionCore-7.3.5#114]
* pets no longer cast spells.
* pet auto-cast is not working.

This commit broke the ability of pets to cast spells.
https://github.com/The-Legion-Preservation-Project/LegionCore-7.3.5/commit/b15d1ec3d9ecb8ac5cf55a0fc115351e0eee8d37

**Comment by jasongdove** [comment]
@3nei please fix in https://github.com/The-Legion-Preservation-Project/LegionCore-7.3.5/pull/116

**Comment by Simonlamb1979** [comment]
I compile the source, but I can't login. When I put my password in and login in the world, it crushed.

My loacle is zhCN.
Here are my config:
OS : win10.21H2
BOOST: boost_1_85_0
OpenSSL:3.1.6
MySQL:mysql8.3.0
GIT:2.26.2
Cmake:3.30.3

Would you mind share your config?
Or tell me what I am doing wrong?

**Comment by jasongdove** [comment]
@Simonlamb1979 please make your own issue or join us in discord to troubleshoot (see README). Please do not post on unrelated issues.

**Comment by Simonlamb1979** [comment]
@jasongdove Sorry, my bad
