### ISSUE TITLE
Crashe.....

### ISSUE THREAD

**Issue by Arshiya051** [The-Legion-Preservation-Project/LegionCore-7.3.5#127]
[_worldserver.exe_[2-11_11-37-53].dmp](https://github.com/user-attachments/files/17606164/_worldserver.exe_.2-11_11-37-53.dmp)
[_worldserver.exe_[2-11_11-37-53].txt](https://github.com/user-attachments/files/17606166/_worldserver.exe_.2-11_11-37-53.txt)
[Server.log](https://github.com/user-attachments/files/17606170/Server.log)
It doesn't enter the server... The server crashes while loading and the game closes.

**Comment by ReyDonovan** [comment]
![image](https://github.com/user-attachments/assets/257d9389-3b03-4713-9c34-cce0ce903f3b)
please build Debug

**Comment by slash-design** [comment]
Have you inserted the Legacy.dll ?

**Comment by Arshiya051** [comment]
> Have you inserted the Legacy.dll ?

No.! from where?

**Comment by jasongdove** [comment]
See https://trinitycore.info/install/Core-Installation/windows-core-installation

> There are four DLL files that need to be manually added to this folder, and you need to copy them over from the following installation/bin directories:
> 
> libmysql.dll →  C:\Program Files\MySQL\MySQL Server 8.x\lib\
> 
> OpenSSL 3 requires the following files:
> 
> legacy.dll
> libssl-3-x64.dll
> libcrypto-3-x64.dll → C:\OpenSSL-Win64\bin

**Comment by ReyDonovan** [comment]
@jasongdove yes, close

**Comment by Arshiya051** [comment]
> Have you inserted the Legacy.dll ?

Ty. It was fixed.
