### ISSUE TITLE
Need to check.....

### ISSUE THREAD

**Issue by Arshiya051** [The-Legion-Preservation-Project/LegionCore-7.3.5#131]
I quickly found the bugs after logging into the server and creating a hero.
First, the maps extracted from your source are incomplete and maps like Dalaran have problems. And the maps that I shared are more complete. Second, the server bugs are still there, for example:
1. There is a problem with the bag. 2. Pat Hunter has a problem. 3. Hunter class scenarios have difficulty getting artifact items. 4. Quests in Pandaria have problems.

**Comment by jasongdove** [comment]
I appreciate the feedback, but this is not a helpful way to report issues (too many, and no details). Please stick to one bug per issue, and please give details like:

1. What you did (steps to repro)
2. What you expected to happen
3. What actually happened

I'll work on an issue template to require this going forward.
