### ISSUE TITLE
about Sql update 

### ISSUE THREAD

**Issue by leewheel** [The-Legion-Preservation-Project/LegionCore-7.3.5#156]
in the 2024_11_08_loot_template_updates.sql has no field list in sql table

**Description:**

Update sql : 

`INSERT INTO `gameobject_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`)`
but the table is:
![image](https://github.com/user-attachments/assets/10f99697-280c-463c-8c88-ed27bdc50ade)
So This is a completely different table

**Expected behaviour:**

**Steps to reproduce the problem:**

test import the sql to gameobject_loot_template

**LC rev. hash/commit:**

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:**

Windows 10

**Comment by jasongdove** [comment]
Please enable and use the automatic update feature in worldserver.conf to ensure you have all updates applied in the correct order.

You are missing https://github.com/The-Legion-Preservation-Project/LegionCore-7.3.5/blob/main/sql/updates/world/2024_11_08_loot_template_rework.sql

##################################################################################################
# UPDATE SETTINGS
#
#    Updates.EnableDatabases
#        Description: A mask that describes which databases shall be updated.
#
#        Following flags are available
#           DATABASE_LOGIN     = 1, // Auth database
#           DATABASE_CHARACTER = 2, // Character database
#           DATABASE_WORLD     = 4, // World database
#           DATABASE_HOTFIX    = 8, // Hotfixes database
#
#        Default:     15 - (All enabled)
#                     4  - (Enable world only)
#                     0  - (All Disabled)

Updates.EnableDatabases = 15

**Comment by leewheel** [comment]
Thanks!
