### ISSUE TITLE
NPC: Drusilla La Salle ( 459 )

### ISSUE THREAD

**Issue by 3nei** [The-Legion-Preservation-Project/LegionCore-7.3.5#178]
**Description:**

NPC: Drusilla La Salle ( 459 ) [5] https://www.wowhead.com/npc=459

DB GUID: 102910, current GUID: GUID Full: 0x00000000000191fe Type: Creature Entry: 459  Low: 102910. 
Faction: 12. 
Entry: 459. 
DisplayID: 3345 (Native: 3345). 
NpcFlags: 51 : Gossip Questgiver Trainer TrainerClass  
NpcFlags2: 0 
UnitFlags: 768 : ImmuneToPC ImmuneToNPC  
DynamicFlags: 0 
Level: 5. 
Health (base): 281. (max): 281. (current): 281. 
Faction Template: 12. 
SpawnTime: Full:2m Remain:0s 
Loot: 0 Pickpocket: 0 Skinning: 0 
InstanceID: 0 
Phasemask: 1 
Armor: 75 
Position: -8926.740234 -195.589005 80.771400. 
AIName: SmartAI ScriptName: 

![WoWScrnShot_112524_101841](https://github.com/user-attachments/assets/d5a46e5f-88d4-4d77-8f98-e95a490c39ee)
![SPP_Wow-64_Nu_TDR2rUH2c8](https://github.com/user-attachments/assets/07bd044c-d8b4-4f4d-93e1-a61b47389e23)

* wrong action on NPC gossip
* act as `mailbox` instead of learning `Dual Specialization`

**Expected behaviour:**

* should learn `Dual Specialization`.

**Steps to reproduce the problem:**

go to Eastern Kingdoms (0), Northshire (6170), Northshire Valley (9), Phase: 1, Difficulty 0, spawnmask 0
`.go xyz -8926.740234 -195.589005 80.771400 0`

**Tested on / issue occurs on:**

Human Warlock 4 [A] in party [5]

**LC rev. hash/commit:**

84b6b462da75+ 2024-11-22 (origin/main branch) (Win64, RelWithDebInfo)
Using SSL version: OpenSSL 3.4.0 22 Oct 2024 (library: OpenSSL 3.4.0 22 Oct 2024)
Using Boost version: 1.85.0
Using MySQL version: 110502
Using CMake version: 3.30.5
Compiled on: Windows 
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./Data/maps. Total size: 900650049 bytes
vmaps directory located in ./Data/vmaps. Total size: 5127494765 bytes
mmaps directory located in ./Data/mmaps. Total size: 6432768328 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS none 
Using World DB: LegionCore World Database 2024-10-23

**Operating system:**

`Windows`

**Comment by jasongdove** [comment]
From https://www.wowhead.com/patchnotes=7.0.3

> Characters can now change between any of their specializations freely. Action bar configurations are saved for each specialization. As a result, Dual Specialization has been removed.

This is an outdated system so the menu option will need to be removed from all trainers.
