### ISSUE TITLE
Quest: Wanted:  "Hogger" ( 176 ) [9]

### ISSUE THREAD

**Issue by 3nei** [The-Legion-Preservation-Project/LegionCore-7.3.5#180]
**Description:**

Quest: Wanted:  "Hogger" ( 176 ) [9]   https://www.wowhead.com/quest=176

NPC: Hogger ( 448 ) [11] https://www.wowhead.com/npc=448

DB GUID: 102514, current GUID: GUID Full: 0x0000000000019072 Type: Creature Entry: 448  Low: 102514. 
Faction: 20. 
Entry: 448. 
DisplayID: 384 (Native: 384). 
NpcFlags: 0 
NpcFlags2: 0 
UnitFlags: 0 
DynamicFlags: 12 : Lootable TrackUnit  
Level: 11. 
Health (base): 1176. (max): 1176. (current): 0. 
Faction Template: 20. 
SpawnTime: Full:2m Remain:3m48s 
Loot: 448 Pickpocket: 448 Skinning: 0 
InstanceID: 0 
Phasemask: 1 
Armor: 98 
Position: -10135.252930 670.992859 35.751114. 
AIName: SmartAI ScriptName: 
![WoWScrnShot_112524_181744](https://github.com/user-attachments/assets/5347e35b-3770-421e-93ae-13d93f9b21e8)

Missing event script

**Expected behaviour:**

* `Hogger` should not be killable.
* Alliance NPCs should spawn when `Hogger`'s health reaches a certain threshold.

**Steps to reproduce the problem:**

go to Eastern Kingdoms (0), Elwynn Forest (12), Hogger Hill (5174), Phase: 1, Difficulty 0, spawnmask 0
`.go xyz -10135.252930 670.992859 35.751114 0`

`.quest add 176`

**Tested on / issue occurs on:**

Human Warlock 9 [A] in party [5]

**LC rev. hash/commit:**

84b6b462da75+ 2024-11-22 (origin/main branch) (Win64, RelWithDebInfo)
Using SSL version: OpenSSL 3.4.0 22 Oct 2024 (library: OpenSSL 3.4.0 22 Oct 2024)
Using Boost version: 1.85.0
Using MySQL version: 110502
Using CMake version: 3.30.5
Compiled on: Windows 
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./Data/maps. Total size: 900650049 bytes
vmaps directory located in ./Data/vmaps. Total size: 5127494765 bytes
mmaps directory located in ./Data/mmaps. Total size: 6432768328 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS none 
Using World DB: LegionCore World Database 2024-10-23

**Operating system:**

`Windows`

**Comment by jasongdove** [comment]
@3nei please test #185 when you have time.

**Comment by 3nei** [comment]
fixed by https://github.com/The-Legion-Preservation-Project/LegionCore-7.3.5/pull/185

* `event` now works correctly
* Alliance NPCs now spawn correctly
* quest completable.

tested on two characters.
