### ISSUE TITLE
Quest: It's Alive! ( 26257 ) [12]

### ISSUE THREAD

**Issue by 3nei** [The-Legion-Preservation-Project/LegionCore-7.3.5#188]
**Description:**

Quest: It's Alive! ( 26257 ) [12]   https://www.wowhead.com/quest=26257

NPC: Overloaded Harvest Golem ( 42601 ) [14] https://www.wowhead.com/npc=42601

DB GUID: 0, current GUID: GUID Full: 0x0000000008c170a4 Type: Vehicle Entry: 42601  Low: 146895012. 
Faction: 1. 
Entry: 42601. 
DisplayID: 367 (Native: 367). 
NpcFlags: 0 
NpcFlags2: 0 
UnitFlags: 16777224 : PvPAttackable PlayerControlled  
DynamicFlags: 0 
Level: 14. 
Health (base): 3384. (max): 3384. (current): 3384. 
Faction Template: 1. 
SpawnTime: Full:5m Remain:0s 
Loot: 0 Pickpocket: 0 Skinning: 0 
InstanceID: 0 
Phasemask: 1 
Armor: 110 
Position: -10188.419922 1441.577515 40.536209. 
AIName: SmartAI ScriptName: 

![WoWScrnShot_112724_091019](https://github.com/user-attachments/assets/f39ba610-f234-49e0-8c9a-82b95b6ba62d)

NPC: Overloaded Harvest Golem ( 42601 ) [14] https://www.wowhead.com/npc=42601
* has incorrect movement speed ( to slow )
* https://www.wowhead.com/spell=79430/rocket-boost#used-by-npc should increase the Overloaded Harvest Golem's speed, but instead, it stuns you in place
* https://www.wowhead.com/spell=79425/reaping-blows it is impossible to hit mobs with this ability

NPC: Energized Harvest Reaper ( 42342 ) [13] https://www.wowhead.com/npc=42342
* does not react to the Overloaded Harvest Golem (only attacks players not in the Overloaded Harvest Golem vehicle)
* frozen in place
* some are stuck in an evade state
* the issue appears to be that the Golem vehicle remains stationary at the location where it was mounted. All subsequent actions occur only in the "camera view," leading to mobs constantly evading because they do not detect a nearby target.

**Expected behaviour:**

* https://youtu.be/P-l1SGom1KE?si=3YYquFZvz1CI8lrl&t=74

**Steps to reproduce the problem:**

go to Eastern Kingdoms (0), Westfall (40), The Molsen Farm (918), Phase: 1, Difficulty 0, spawnmask 0
`.go xyz -10188.419922 1441.577515 40.536209 0`

`.quest add 26257`

**Tested on / issue occurs on:**

Human Warlock 12 [A]

**LC rev. hash/commit:**

12179ae80c0a+ 2024-11-26 18:20:09 -0600 (main branch) (Win64, RelWithDebInfo)
Using SSL version: OpenSSL 3.4.0 22 Oct 2024 (library: OpenSSL 3.4.0 22 Oct 2024)
Using Boost version: 1.85.0
Using MySQL version: 110502
Using CMake version: 3.30.5
Compiled on: Windows 
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./Data/maps. Total size: 900650049 bytes
vmaps directory located in ./Data/vmaps. Total size: 5127494765 bytes
mmaps directory located in ./Data/mmaps. Total size: 6432768328 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS none 
Using World DB: LegionCore World Database 2024-10-23

**Operating system:**

`Windows`

**Comment by jasongdove** [comment]
Lots of issues with this one, fortunately TCPP has a good implementation to reference. @3nei please try https://github.com/The-Legion-Preservation-Project/LegionCore-7.3.5/pull/199 when you have time.

**Comment by 3nei** [comment]
* [Overloaded Harvest Golem](https://www.wowhead.com/npc=42601) - movement speed fixed now
* [Rocket Boost#used By Npc](https://www.wowhead.com/spell=79430) - fixed
* [Reaping Blows](https://www.wowhead.com/spell=79425) - still impossible to hit mobs with this ability
* [Energized Harvest Reaper](https://www.wowhead.com/npc=42342) - continues to evade and not attack vehicles

https://youtu.be/d3XdPYUVZX0

**Comment by jasongdove** [comment]
Thanks, with more testing I can repro the evade locally now. Will investigate.

**Comment by jasongdove** [comment]
I think it has more to do with the threat system than an incorrect location. If you enter the vehicle, wait a second or two, then `.gm on` and get in aggro range, it will behave much better.

AshamaneCore handles the threat correctly, so I'm comparing with that.

**Comment by jasongdove** [comment]
#199 was getting pretty big so I merged what I had.

I *think* the only remaining issue is that https://www.wowhead.com/spell=79425/reaping-blows does not show a channeled cast bar, which makes it a little awkward to use, but it otherwise works correctly as far as I can tell.

Please let me know if anything else seems incorrect.

**Comment by 3nei** [comment]
It is Blizzlike now! Great job.
Some rare evade events are happening, but it could be due to the threat system, as you mentioned above.

**Comment by kaligun** [comment]
![Screenshot 2024-12-01 195536](https://github.com/user-attachments/assets/3d12c806-7433-4b8c-a1c1-bbd9d2a2a524)
![Screenshot 2024-12-01 195543](https://github.com/user-attachments/assets/fc2bfe83-4bae-42a2-9f43-d80a4bfd34a5)
![Screenshot 2024-12-01 195552](https://github.com/user-attachments/assets/356aa905-9a3e-435d-a0ba-244f5959f209)
HI ! [Harvest Watcher Heart] this item works everywhere even i can get anduin too! thank you !

**Comment by 3nei** [comment]
Haha, that's a Blizzard-level bug!

**Comment by jasongdove** [comment]
Will need to update `spell_westfall_wake_harvest_golem::CheckTarget`.

**Comment by jasongdove** [comment]
> Will need to update `spell_westfall_wake_harvest_golem::CheckTarget`.

Actually, this is wrong. It's maybe a larger core bug. The spell effect should already be limiting the target. Scroll all the way to the right here https://wago.tools/db2/SpellEffect?build=7.3.5.26972&filter[SpellID]=79436&page=1

**Comment by 3nei** [comment]
* fixed with #220 

![WoWScrnShot_120124_231418](https://github.com/user-attachments/assets/b466df98-05d6-493c-a5fb-6532ddcc0f55)
