### ISSUE TITLE
Quests and item artifact hunter

### ISSUE THREAD

**Issue by Arshiya051** [The-Legion-Preservation-Project/LegionCore-7.3.5#77]
hello . Hunter quests and Hunter artifact item quests have problems. Can you write a script for it and solve it?

**Comment by Arshiya051** [comment]
yes When a Class Hunter completes the initial quests to enter the Patch Legion and enters Dalaran Patch Legion, he receives the quest related to getting the artifact item and enters the scenario to get the artifact item. Their scenarios have problems and bugs.
@slash-design

**Comment by slash-design** [comment]
@Arshiya051 
You mean this one, right ??

https://youtu.be/AoCALNiQj9k?si=U2TpzBRbb_pER_v7

**Comment by Arshiya051** [comment]
Yes....
@slash-design
